### ISSUE TITLE
Off topic

### ISSUE THREAD

**Issue by mbason** [JordekFluffball/PururinTime#2]
Hey dude,
So you don't know me and I don't know you. But we have something in common if you check this link https://namemc.com/profile/JordekFluffball you might understand. So is there anyway I could possibly get my account back? I've already contacted mojang about this and am waiting for the transaction id from paypal. If this is not you nevermind. If it is tho hit me up on twitter @mbason or here either one.

**Comment by mysticpoisen** [comment]
Hi there, I'm not sure what you're asking, but I don't have your username
or account or whatever. I'm not sure how you got this email, sorry. Good
luck in getting it back.
